config/routes.rb
Rails.application.routes.draw do
  get 'game', to: 'playing#game'

  get 'score', to: 'playing#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/playing_controller.rb
class PlayingController < ApplicationController
  def game
    @answer = params[:answer]
    session[:grid] = generate_grid
  end

  def score
    end_time = Time.now
    @answer = params[:answer]
    @grid = params[:grid].gsub(/\W/,' ')
    @time = (end_time - params[:start_time].to_datetime).round(2)
    @translation = get_translation(@answer)
    @score = compute_score(@answer, @time)
  end

  private

  def generate_grid
    grid = []
    10.times{ grid << ('A'..'Z').to_a.sample }
    grid
  end

  def compute_score(answer, time_taken)
    score = (time_taken > 60.0) ? 0 : answer.size * (1.0 - time_taken / 60.0)
    score.round(2)
  end

  def get_translation(attempt)
    api = 'https://api-platform.systran.net/translation/text/translate?source=en&target=fr&key='
    key = 'cdf01b7c-89ee-48fe-a21f-14133d773540'
    url = "#{api}#{key}&input=#{attempt}"
    translation = JSON.parse(open(url).read)
    if translation["outputs"][0]["output"] == attempt
     return nil
    else
     return translation["outputs"][0]["output"]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playing_helper.rb
module PlayingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/playing/game.html.erb
<h1>Playing the longest word game</h1>

<h2>Grid</h2>

<div>
  <%= session[:grid] %>
</div>

<br>
<br>

<form action="<%= score_path %>" method="get">
  <label for="answer">Type your answer here:</label>
  <input type="text" id="answer" name="answer" placeholder="Your answer">
  <input type="hidden" name="grid" value="<%= @grid %>">
  <input type="hidden" name="start_time" value="<%= Time.now %>">
  <input type="submit" value="Go On!">
</form>

app/views/playing/score.html.erb
<h1>Playing the longest word game</h1>

<h3>The grid was:</h3>
<%= session[:grid] %>

<h3>Your answer:</h3>
<%= @answer %>

<h3>Your translation:</h3>
<%= @translation%>

<h3>Your time:</h3>
<%= @time %>

<h2>Your score:</h2>
<%= @score %>